window.STRIKEZONE_PLAYERS = [
  // INTERNACIONALES — las figuras activas usan simulación de prototipo para evitar presentar un corte no verificado como oficial.
  {id:'shohei-ohtani',name:'Shohei Ohtani',team:'Los Angeles Dodgers',category:'internacional',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.292'],['HR','35'],['RBI','86'],['OPS','.965']],bio:'Carta internacional pensada para el reto de bateo. Las cifras mostradas corresponden a una temporada simulada utilizada para el reto de bateo.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=shohei-ohtani',ar:'trofeo'},
  {id:'babe-ruth',name:'Babe Ruth',team:'New York Yankees',category:'internacional',image:'assets/players/placeholder.svg',statsLabel:'MLB · CARRERA',stats:[['AVG','.342'],['HR','714'],['RBI','2214'],['H','2873']],bio:'Una de las figuras más influyentes en la historia de las Grandes Ligas; combinó poder ofensivo con una etapa destacada como lanzador.',source:'https://www.mlb.com/news/babe-ruth-s-top-10-career-statistics-c163792958',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=babe-ruth'},
  {id:'aaron-judge',name:'Aaron Judge',team:'New York Yankees',category:'internacional',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.286'],['HR','42'],['RBI','101'],['OPS','1.012']],bio:'Carta internacional centrada en poder al bate. Esta carta utiliza una temporada simulada para representar su perfil ofensivo dentro de la colección.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=aaron-judge'},
  {id:'ichiro-suzuki',name:'Ichiro Suzuki',team:'Seattle Mariners',category:'internacional',image:'assets/players/ichiro-suzuki.png',statsLabel:'MLB · CARRERA',stats:[['AVG','.311'],['HR','117'],['RBI','780'],['H','3089']],bio:'Ícono japonés de Seattle, reconocido por contacto, velocidad y defensa. Su carta destaca contacto, velocidad y defensa dentro de la categoría Internacionales.',source:'https://www.mlb.com/news/ichiro-suzuki-hall-of-fame-career-stats',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=ichiro-suzuki',arCard:'ichiro-suzuki',qr:'assets/qr/ichiro-suzuki-ar.png'},
  {id:'derek-jeter',name:'Derek Jeter',team:'New York Yankees',category:'internacional',image:'assets/players/derek-jeter.png',statsLabel:'MLB · CARRERA',stats:[['AVG','.310'],['HR','260'],['RBI','1311'],['H','3465']],bio:'Shortstop y capitán histórico de los Yankees durante dos décadas; su perfil encaja en la colección internacional por liderazgo y trayectoria.',source:'https://www.mlb.com/player/derek-jeter-116539',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=derek-jeter',arCard:'derek-jeter',qr:'assets/qr/derek-jeter-ar.png'},
  {id:'yadier-molina',name:'Yadier Molina',team:'St. Louis Cardinals',category:'internacional',image:'assets/players/yadier-molina.png',statsLabel:'MLB · CARRERA',stats:[['AVG','.277'],['HR','176'],['RBI','1022'],['H','2168']],bio:'Receptor puertorriqueño reconocido por defensa, manejo de pitcheo y liderazgo con St. Louis.',source:'https://www.mlb.com/player/yadier-molina-425877',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=yadier-molina',arCard:'yadier-molina',qr:'assets/qr/yadier-molina-ar.png'},
  {id:'miguel-cabrera',name:'Miguel Cabrera',team:'Detroit Tigers',category:'internacional',image:'assets/players/placeholder.svg',statsLabel:'MLB · CARRERA',stats:[['AVG','.306'],['HR','511'],['RBI','1881'],['H','3174']],bio:'Bateador venezolano, ganador de Triple Corona en 2012 y una de las grandes figuras ofensivas de su generación.',source:'https://www.mlb.com/player/miguel-cabrera-408234',primaryLabel:'Jugar reto',primaryHref:'juego.html?player=miguel-cabrera'},

  // LEYENDAS — Héctor usa datos históricos; el resto queda completo con simulación declarada hasta elegir una fuente histórica definitiva.
  {id:'hector-espino',name:'Héctor Espino',team:'Sultanes de Monterrey',category:'leyenda',image:'assets/players/hector-espino.png',statsLabel:'LMB · CARRERA',stats:[['AVG','.335'],['HR','453'],['RBI','1573'],['H','2752']],bio:'“El Maestro” es una de las grandes figuras del beisbol mexicano. Su carta conecta la categoría Leyendas con trivia y una experiencia de pelota 3D.',source:'https://www.sultanes.com.mx/noticias/hector-espino-leyenda-del-beisbol-mexicano',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=hector-espino',ar:'pelota'},
  {id:'epitacio-torres',name:'Epitacio “La Mala” Torres',team:'Liga Mexicana de Beisbol',category:'leyenda',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.318'],['HR','12'],['RBI','74'],['H','164']],bio:'Leyenda incluida en el archivo de StrikeZone. La carta usa una línea estadística simulada para acompañar su recorrido histórico.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=epitacio-torres'},
  {id:'daniel-rios-leyenda',name:'Daniel Ríos',team:'Liga Mexicana de Beisbol',category:'leyenda',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['W','14'],['ERA','3.42'],['SO','118'],['IP','151.0']],bio:'Perfil histórico presentado como lanzador dentro de la colección. La ficha usa estadísticas simuladas para representar un perfil de lanzador.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=daniel-rios-leyenda'},
  {id:'arturo-gonzalez',name:'Arturo González',team:'Liga Mexicana de Beisbol',category:'leyenda',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.301'],['HR','18'],['RBI','82'],['H','146']],bio:'Carta de archivo histórico para la sección Leyendas. Las métricas corresponden a una temporada simulada de la colección.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=arturo-gonzalez'},
  {id:'andres-mora',name:'Andrés Mora',team:'Liga Mexicana de Beisbol',category:'leyenda',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.312'],['HR','27'],['RBI','93'],['H','155']],bio:'Carta de Leyendas pensada para conectar colección y trivia. Los valores corresponden a una temporada simulada dentro de StrikeZone.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=andres-mora'},
  {id:'miguel-flores',name:'Miguel Flores',team:'Liga Mexicana de Beisbol',category:'leyenda',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.296'],['HR','15'],['RBI','68'],['H','139']],bio:'Perfil de archivo LMB dentro de la categoría Leyendas. La tarjeta utiliza una temporada simulada para acompañar su perfil de leyenda.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=miguel-flores'},
  {id:'juan-navarrete',name:'Juan Navarrete',team:'Liga Mexicana de Beisbol',category:'leyenda',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.287'],['HR','11'],['RBI','59'],['H','132']],bio:'Figura incluida en la colección histórica. Los datos del reverso corresponden a una temporada simulada para esta carta.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Ir a trivia',primaryHref:'trivia.html?player=juan-navarrete'},

  // CAPITANES — colección directa.
  {id:'ramiro-pena',name:'Ramiro Peña',team:'Sultanes de Monterrey',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'LMB 2026',stats:[['AVG','.261'],['HR','6'],['RBI','26'],['SLG','.422']],bio:'Infielder veterano de Sultanes. En 2026 registró 42 juegos y su carta se colecciona directamente dentro de StrikeZone.',source:'https://lmb.com.mx/jugador/455369',primaryLabel:'Coleccionar',primaryAction:'collect'},
  {id:'isaac-rodriguez',name:'Isaac Rodríguez',team:'Toros de Tijuana',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'LMB · HITO 2026',stats:[['H','900+'],['DEBUT','2015'],['ROL','2B'],['CLUB','TIJ']],bio:'Capitán y referente de Toros de Tijuana. En 2026 alcanzó más de 900 imparables de carrera en LMB.',source:'https://torosdetijuana.com/index.php/isaac-rodriguez-mantiene-su-enfoque-en-el-exito-colectivo/2026/06/',primaryLabel:'Coleccionar',primaryAction:'collect'},
  {id:'manny-rodriguez',name:'Manny Rodríguez',team:'Liga Mexicana de Beisbol',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.304'],['HR','14'],['RBI','72'],['OPS','.841']],bio:'Carta de Capitán preparada para colección directa. Las cifras corresponden a una temporada simulada dentro de la colección.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Coleccionar',primaryAction:'collect'},
  {id:'wilmer-rios',name:'Wilmer Ríos',team:'Acereros de Monclova',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'LMB 2026 · PITCHEO',stats:[['W','3'],['ERA','4.80'],['SO','65'],['IP','84.1']],bio:'Lanzador mexicano de Acereros. Su reverso cambia a métricas de pitcheo para demostrar que las cartas no están limitadas a bateadores.',source:'https://lmb.com.mx/jugador/658140',primaryLabel:'Coleccionar',primaryAction:'collect'},
  {id:'didi-gregorius',name:'Didi Gregorius',team:'Algodoneros de Unión Laguna',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'LMB 2026',stats:[['AVG','.222'],['HR','3'],['RBI','18'],['OBP','.335']],bio:'Infielder con experiencia de Grandes Ligas. En el corte oficial LMB 2026 aparece con Unión Laguna.',source:'https://lmb.com.mx/jugador/544369',primaryLabel:'Coleccionar',primaryAction:'collect'},
  {id:'henry-urrutia',name:'Henry Urrutia',team:'Conspiradores de Querétaro',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'LMB 2026',stats:[['AVG','.320'],['HR','13'],['RBI','61'],['SLG','.484']],bio:'Bateador cubano-mexicano con experiencia en MLB y LMB. Esta carta se conserva en tu lista de Capitanes aunque su club 2026 no pertenece a la Zona Norte.',source:'https://lmb.com.mx/jugador/625329',primaryLabel:'Coleccionar',primaryAction:'collect'},
  {id:'kennys-vargas',name:'Kennys Vargas',team:'Liga Mexicana de Beisbol',category:'capitan',image:'assets/players/placeholder.svg',statsLabel:'TEMPORADA SIMULADA',stats:[['AVG','.291'],['HR','19'],['RBI','67'],['OPS','.879']],bio:'Primera base puertorriqueño con trayectoria en LMB. La ficha utiliza una temporada simulada para representar su perfil ofensivo.',sourceNote:'Estadísticas simuladas para la experiencia',primaryLabel:'Coleccionar',primaryAction:'collect'}
];
