(() => {
  const qs=[{q:'¿En qué año se fundó la Liga Mexicana de Beisbol?',a:['1910','1925','1946'],correct:1,why:'La temporada inaugural de la LMB se disputó en 1925.'},{q:'¿Cuántos HR conectó Héctor Espino en su carrera de LMB?',a:['453','714','419'],correct:0,why:'La ficha histórica usada por StrikeZone registra 453 cuadrangulares.'},{q:'¿Qué equipo aparece como líder de la Zona Norte en el corte 2026 del proyecto?',a:['Toros de Tijuana','Sultanes de Monterrey','Charros de Jalisco'],correct:0,why:'El corte integrado al prototipo coloca a Toros de Tijuana al frente.'}];
  const box=document.querySelector('[data-question]'),answers=document.querySelector('[data-answers]'),step=document.querySelector('[data-step]'),feedback=document.querySelector('[data-trivia-feedback]'),bar=document.querySelector('[data-progress]'),result=document.querySelector('[data-result]'),copy=document.querySelector('[data-result-copy]'),reward=document.querySelector('[data-trivia-reward]');if(!box)return;
  const id=new URLSearchParams(location.search).get('player')||'hector-espino',player=(window.STRIKEZONE_PLAYERS||[]).find(p=>p.id===id)||{id,name:'Carta de leyenda'};document.querySelector('[data-trivia-player]').textContent=player.name;
  if(!window.StrikeZoneRewards.session()){window.StrikeZoneRewards.requireSession(`trivia.html?player=${encodeURIComponent(id)}`);return}
  let i=0,score=0,busy=false;
  function finish(){box.closest('[data-question-card]').hidden=true;result.hidden=false;result.querySelector('[data-final-score]').textContent=`${score}/${qs.length}`;if(score===qs.length){window.StrikeZoneRewards.unlock(player,'trivia');copy.textContent=`${player.name} quedó desbloqueada y se agregó a tu colección.`;reward.hidden=false;window.StrikeZoneFeedback?.show('¡Carta desbloqueada!')}else{copy.textContent='Necesitas responder correctamente las tres preguntas. Puedes intentarlo otra vez.'}}
  function render(){if(i>=qs.length){finish();return}const q=qs[i];box.textContent=q.q;answers.innerHTML=q.a.map((x,n)=>`<button type="button" class="answer" data-answer="${n}">${x}</button>`).join('');step.textContent=`${i+1} / ${qs.length}`;bar.style.width=`${(i/qs.length)*100}%`;feedback.textContent='';busy=false}
  answers.addEventListener('click',e=>{const b=e.target.closest('[data-answer]');if(!b||busy)return;busy=true;const q=qs[i],ok=Number(b.dataset.answer)===q.correct;if(ok){score++;b.classList.add('is-correct');feedback.textContent=`Correcto. ${q.why}`}else{b.classList.add('is-wrong');answers.querySelector(`[data-answer="${q.correct}"]`)?.classList.add('is-correct');feedback.textContent=`Respuesta: ${q.a[q.correct]}. ${q.why}`}setTimeout(()=>{i++;render()},1050)});render();
})();
