(() => {
  const canvas=document.querySelector('[data-editor-canvas]'); if(!canvas)return;
  const ctx=canvas.getContext('2d',{willReadFrequently:true}); const temp=document.createElement('canvas'),tctx=temp.getContext('2d',{willReadFrequently:true});
  const img=document.querySelector('[data-editor-image]'),video=document.querySelector('[data-editor-video]');
  const status=document.querySelector('[data-editor-status]'),titleEl=document.querySelector('[data-editor-title]'),kindEl=document.querySelector('[data-editor-kind]');
  const play=document.querySelector('[data-video-play]'),save=document.querySelector('[data-save-media]'),download=document.querySelector('[data-download-media]'),record=document.querySelector('[data-record-video]');
  const intensity=document.querySelector('[data-intensity]'),intensityOut=document.querySelector('[data-intensity-value]');
  const filterButtons=[...document.querySelectorAll('[data-edit-filter]')];
  const p=new URLSearchParams(location.search),src=p.get('src')||'',type=p.get('type')==='video'?'video':'image',title=p.get('title')||'Contenido StrikeZone';
  let filter='normal',raf=0,loaded=false,recording=false,recorder=null,chunks=[],pendingDownload=false,lastExport=null;
  const names={normal:'Original',blur:'Desenfoque',pixel:'Pixelado',thermal:'Cámara térmica',color:'Ajuste de color',pastel:'Pastel',soft:'Suavizado',saturate:'Alta saturación'};
  titleEl.textContent=title; kindEl.textContent=type==='video'?'VIDEO EDITABLE':'IMAGEN EDITABLE';
  function setStatus(text){status.textContent=text}
  function setSize(w,h){const max=1280,scale=Math.min(1,max/w);canvas.width=Math.max(2,Math.round(w*scale));canvas.height=Math.max(2,Math.round(h*scale));temp.width=canvas.width;temp.height=canvas.height}
  function thermalize(image,amount){const d=image.data,a=amount/100;for(let i=0;i<d.length;i+=4){const or=d[i],og=d[i+1],ob=d[i+2],lum=.299*or+.587*og+.114*ob;let r,g,b;if(lum<64){r=0;g=lum*2;b=150+lum*1.6}else if(lum<128){const t=(lum-64)/64;r=0;g=128+127*t;b=255-210*t}else if(lum<192){const t=(lum-128)/64;r=255*t;g=255;b=45-45*t}else{const t=(lum-192)/63;r=255;g=255-220*t;b=0}d[i]=or*(1-a)+r*a;d[i+1]=og*(1-a)+g*a;d[i+2]=ob*(1-a)+b*a}return image}
  function draw(source){if(!loaded||!canvas.width)return;const amount=Number(intensity.value||70);ctx.save();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.filter='none';ctx.imageSmoothingEnabled=true;
    if(filter==='pixel'){const blocks=Math.max(10,Math.round(48-(amount/100)*34)),sw=Math.max(20,Math.round(canvas.width/blocks)),sh=Math.max(15,Math.round(canvas.height/blocks));temp.width=sw;temp.height=sh;tctx.imageSmoothingEnabled=true;tctx.drawImage(source,0,0,sw,sh);ctx.imageSmoothingEnabled=false;ctx.drawImage(temp,0,0,sw,sh,0,0,canvas.width,canvas.height)}
    else if(filter==='thermal'){temp.width=canvas.width;temp.height=canvas.height;tctx.drawImage(source,0,0,canvas.width,canvas.height);ctx.putImageData(thermalize(tctx.getImageData(0,0,canvas.width,canvas.height),amount),0,0)}
    else {const t=amount/100;if(filter==='blur')ctx.filter=`blur(${(1+t*11).toFixed(1)}px) saturate(1.05)`;if(filter==='color')ctx.filter=`saturate(${1+t*.9}) contrast(${1+t*.18}) brightness(${1+t*.05})`;if(filter==='pastel')ctx.filter=`saturate(${1-t*.35}) contrast(${1-t*.18}) brightness(${1+t*.15})`;if(filter==='soft')ctx.filter=`blur(${t*2.2}px) saturate(${1-t*.12}) brightness(${1+t*.06})`;if(filter==='saturate')ctx.filter=`saturate(${1+t*1.65}) contrast(${1+t*.08})`;ctx.drawImage(source,0,0,canvas.width,canvas.height);if(filter==='pastel'){ctx.fillStyle=`rgba(255,236,221,${.06+t*.13})`;ctx.fillRect(0,0,canvas.width,canvas.height)}}ctx.restore()}
  function loop(){if(type==='video'&&loaded)draw(video);raf=requestAnimationFrame(loop)}
  filterButtons.forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.editFilter;filterButtons.forEach(x=>x.classList.toggle('is-active',x===b));if(type==='image')draw(img);setStatus(`${names[filter]} aplicado`);window.StrikeZoneFeedback?.show(`${names[filter]} aplicado`)}));
  intensity.addEventListener('input',()=>{intensityOut.textContent=`${intensity.value}%`;if(type==='image')draw(img)});
  if(type==='image'){img.crossOrigin='anonymous';img.onload=()=>{setSize(img.naturalWidth,img.naturalHeight);loaded=true;draw(img);setStatus('Imagen lista para editar')};img.onerror=()=>setStatus('No se pudo cargar la imagen.');img.src=src;document.querySelectorAll('[data-video-only]').forEach(x=>x.hidden=true)}
  else {video.crossOrigin='anonymous';video.src=src;video.muted=true;video.playsInline=true;video.addEventListener('loadedmetadata',()=>{setSize(video.videoWidth,video.videoHeight);loaded=true;draw(video);setStatus('Video listo. Reproduce y aplica cualquier filtro.')});video.addEventListener('ended',()=>{play.textContent='Reproducir';if(recording)stopRecording()});document.querySelectorAll('[data-image-only]').forEach(x=>x.hidden=true)}
  play?.addEventListener('click',async()=>{if(video.paused){await video.play();play.textContent='Pausar'}else{video.pause();play.textContent='Reproducir'}});
  const canvasBlob=(mime='image/jpeg')=>new Promise(r=>canvas.toBlob(r,mime,mime==='image/jpeg'?.93:undefined));
  async function saveImage(doDownload=false){if(!loaded)return;if(!doDownload&&!window.StrikeZoneSession?.require(`${location.pathname.split('/').pop()}${location.search}`))return;const blob=await canvasBlob('image/jpeg');if(!blob)return;if(doDownload){downloadBlob(blob,`strikezone-${slug(title)}-${filter}.jpg`);setStatus('Imagen descargada')}else{await window.StrikeZonePhotos.add(blob,names[filter],{type:'image',title,source:'galeria'});setStatus('Imagen guardada en tu perfil');window.StrikeZoneFeedback?.show('Imagen guardada en Mis medios')}}
  function slug(v){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  function downloadBlob(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1200)}
  async function startRecording(downloadAfter=false){if(!loaded||recording)return;if(!downloadAfter&&!window.StrikeZoneSession?.require(`${location.pathname.split('/').pop()}${location.search}`))return;if(!canvas.captureStream||!window.MediaRecorder){setStatus('Este navegador no permite exportar video filtrado.');return}pendingDownload=downloadAfter;chunks=[];const stream=canvas.captureStream(30);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';recorder=new MediaRecorder(stream,{mimeType:mime});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{recording=false;record?.classList.remove('button-dark');record.textContent='Guardar video filtrado';const blob=new Blob(chunks,{type:mime});lastExport=blob;if(pendingDownload){downloadBlob(blob,`strikezone-${slug(title)}-${filter}.webm`);setStatus('Video filtrado descargado')}else{await window.StrikeZonePhotos.add(blob,names[filter],{type:'video',title,source:'galeria'});setStatus('Video filtrado guardado en tu perfil');window.StrikeZoneFeedback?.show('Video guardado en Mis medios')}pendingDownload=false};recorder.start(250);recording=true;record?.classList.add('button-dark');record.textContent='Detener y guardar';video.currentTime=0;await video.play();play.textContent='Pausar';setStatus('Exportando video con filtro… se guardará al terminar.')}
  function stopRecording(){if(recording&&recorder?.state!=='inactive'){recorder.stop();video.pause();play.textContent='Reproducir'}}
  record?.addEventListener('click',()=>recording?stopRecording():startRecording(false));
  save?.addEventListener('click',()=>type==='image'?saveImage(false):startRecording(false));
  download?.addEventListener('click',()=>type==='image'?saveImage(true):startRecording(true));
  raf=requestAnimationFrame(loop); addEventListener('beforeunload',()=>{cancelAnimationFrame(raf);if(recording)stopRecording()});
})();
