(() => {
  const video=document.querySelector('[data-fan-video]'),canvas=document.querySelector('[data-fan-canvas]'); if(!video||!canvas)return;
  const ctx=canvas.getContext('2d',{willReadFrequently:true}),placeholder=document.querySelector('[data-fan-placeholder]'),status=document.querySelector('[data-fan-status]');
  const start=document.querySelector('[data-fan-start]'),switchBtn=document.querySelector('[data-fan-switch]'),capture=document.querySelector('[data-fan-capture]'),download=document.querySelector('[data-fan-download]');
  const filterButtons=[...document.querySelectorAll('[data-fan-filter]')], visualButtons=[...document.querySelectorAll('[data-fan-visual]')];
  let stream=null,facing='user',overlay='helmet',visual='normal',raf=0,faceBox=null,lastDetect=0,detector=null;
  try{ if('FaceDetector' in window) detector=new FaceDetector({fastMode:true,maxDetectedFaces:1}); }catch{}
  const names={none:'Sin accesorio',helmet:'Casco de bateador',cap:'Gorra StrikeZone',paint:'Pintura de afición'};
  function setStatus(t){status.textContent=t}
  function roundRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
  function drawHelmet(b){const x=b.x,y=b.y,w=b.width,h=b.height;ctx.save();ctx.lineWidth=Math.max(4,w*.025);ctx.strokeStyle='#d8dfdf';ctx.fillStyle='#142f54';ctx.beginPath();ctx.ellipse(x+w*.5,y+h*.04,w*.57,h*.36,0,Math.PI,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#f7f7f2';ctx.font=`900 ${Math.max(18,w*.10)}px sans-serif`;ctx.textAlign='center';ctx.fillText('SZ',x+w*.5,y-h*.02);ctx.strokeStyle='#183b67';ctx.lineWidth=Math.max(3,w*.018);ctx.beginPath();ctx.moveTo(x+w*.05,y+h*.14);ctx.lineTo(x+w*.13,y+h*.54);ctx.lineTo(x+w*.87,y+h*.54);ctx.lineTo(x+w*.95,y+h*.14);ctx.stroke();for(let i=1;i<5;i++){const xx=x+w*(.13+i*.148);ctx.beginPath();ctx.moveTo(xx,y+h*.25);ctx.lineTo(xx,y+h*.54);ctx.stroke()}ctx.restore()}
  function drawCap(b){const x=b.x,y=b.y,w=b.width,h=b.height;ctx.save();ctx.fillStyle='#122845';ctx.strokeStyle='#d13a38';ctx.lineWidth=Math.max(4,w*.026);ctx.beginPath();ctx.ellipse(x+w*.5,y+h*.055,w*.48,h*.23,0,Math.PI,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.ellipse(x+w*.62,y+h*.13,w*.42,h*.09,-.15,0,Math.PI*2);ctx.fillStyle='#c83534';ctx.fill();ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(16,w*.09)}px sans-serif`;ctx.textAlign='center';ctx.fillText('SZ',x+w*.5,y+h*.035);ctx.restore()}
  function drawPaint(b){const x=b.x,y=b.y,w=b.width,h=b.height;ctx.save();ctx.lineCap='round';ctx.lineWidth=Math.max(7,w*.035);const ys=[.47,.52,.57],colors=['#2f9e62','#f8f8f4','#cf3e38'];for(let side of [.18,.68])ys.forEach((yy,i)=>{ctx.strokeStyle=colors[i];ctx.beginPath();ctx.moveTo(x+w*side,y+h*yy);ctx.lineTo(x+w*(side+.15),y+h*(yy+.02));ctx.stroke()});ctx.restore()}
  function defaultFace(){return{x:canvas.width*.28,y:canvas.height*.18,width:canvas.width*.44,height:canvas.height*.58}}
  async function detect(now){if(!detector||video.readyState<2||now-lastDetect<350)return;lastDetect=now;try{const faces=await detector.detect(video);if(faces[0]?.boundingBox){const b=faces[0].boundingBox;faceBox={x:canvas.width-(b.x+b.width),y:b.y,width:b.width,height:b.height}}}catch{}}
  function drawFrame(now){if(video.readyState>=2&&canvas.width){ctx.save();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.translate(canvas.width,0);ctx.scale(-1,1);ctx.filter='none';if(visual==='pastel')ctx.filter='saturate(.72) contrast(.9) brightness(1.12)';if(visual==='saturate')ctx.filter='saturate(1.85) contrast(1.06)';ctx.drawImage(video,0,0,canvas.width,canvas.height);ctx.restore();const b=faceBox||defaultFace();if(overlay==='helmet')drawHelmet(b);if(overlay==='cap')drawCap(b);if(overlay==='paint')drawPaint(b);detect(now)}raf=requestAnimationFrame(drawFrame)}
  async function openCamera(){if(!navigator.mediaDevices?.getUserMedia){setStatus('Tu navegador no permite usar la cámara.');return}stream?.getTracks().forEach(t=>t.stop());try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:960},height:{ideal:720}},audio:false});video.srcObject=stream;video.playsInline=true;video.muted=true;await video.play();canvas.width=video.videoWidth||960;canvas.height=video.videoHeight||720;placeholder.hidden=true;faceBox=null;setStatus(detector?'Cámara activa · seguimiento facial disponible':'Cámara activa · ajuste visual centrado');window.StrikeZoneFeedback?.show('Cámara Fan activa')}catch{setStatus('No se pudo abrir la cámara. Revisa el permiso del navegador.')}}
  filterButtons.forEach(b=>b.addEventListener('click',()=>{overlay=b.dataset.fanFilter;filterButtons.forEach(x=>x.classList.toggle('is-active',x===b));setStatus(`${names[overlay]} seleccionado`)}));
  visualButtons.forEach(b=>b.addEventListener('click',()=>{visual=b.dataset.fanVisual;visualButtons.forEach(x=>x.classList.toggle('is-active',x===b));setStatus(`Acabado ${b.textContent.trim()} aplicado`)}));
  start?.addEventListener('click',openCamera);switchBtn?.addEventListener('click',async()=>{facing=facing==='user'?'environment':'user';await openCamera()});
  const blob=()=>new Promise(r=>canvas.toBlob(r,'image/jpeg',.93));
  capture?.addEventListener('click',async()=>{if(!window.StrikeZoneSession?.require('foto-fan.html'))return;if(!stream){setStatus('Activa la cámara primero.');return}const b=await blob();if(!b)return;await window.StrikeZonePhotos.add(b,`${names[overlay]} · ${visual}`,{type:'image',title:'Foto Fan StrikeZone',source:'foto-fan'});window.StrikeZoneFeedback?.show('Foto Fan guardada en tu perfil');setStatus('Captura guardada en Mis medios')});
  download?.addEventListener('click',async()=>{if(!stream){setStatus('Activa la cámara primero.');return}const b=await blob();if(!b)return;const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`strikezone-fan-${overlay}-${Date.now()}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setStatus('Foto descargada')});
  raf=requestAnimationFrame(drawFrame);addEventListener('beforeunload',()=>{cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop())});
})();
