window.STRIKEZONE_AR_CARDS = {
  'yadier-molina': {
    id: 'yadier-molina',
    name: 'Yadier Molina',
    team: 'St. Louis Cardinals',
    category: 'INTERNACIONAL',
    targetImage: 'assets/cards/yadier-molina-back.png',
    // El reverso completo de la tarjeta (incluido el QR) es el target de MindAR.
    // El mismo reverso impreso abre la experiencia y después sirve como marcador AR.
    mindFile: null,
    compileTarget: true,
    markerImage: 'assets/cards/yadier-molina-back.png',
    model: 'assets/ar/models/pelota-yadier.glb',
    modelLabel: 'Pelota 3D · modelo propio',
    features: { animations: true, info: true, narration: false, video: false, effects: true },
    qr: 'assets/qr/yadier-molina-ar.png',
    stats: [['AVG','.277'],['HR','176'],['RBI','1022'],['H','2168']],
    bio: 'Receptor puertorriqueño reconocido por defensa, manejo de pitcheo y liderazgo con St. Louis.',
    modelScale: 0.42,
    baseZ: 0.20,
    number: '45',
    role: 'CATCHER',
    playerImage: 'assets/players/yadier-molina.png'
  },
  'derek-jeter': {
    id: 'derek-jeter',
    name: 'Derek Jeter',
    team: 'New York Yankees',
    category: 'INTERNACIONAL',
    targetImage: 'assets/cards/derek-jeter-front.png',
    mindFile: null,
    compileTarget: true,
    markerImage: 'assets/cards/derek-jeter-front.png',
    model: 'assets/ar/models/pelota.glb',
    modelLabel: 'Pelota 3D · modelo provisional',
    features: { animations: true, info: true, narration: false, video: false, effects: true },
    qr: 'assets/qr/derek-jeter-ar.png',
    stats: [['AVG','.310'],['HR','260'],['RBI','1311'],['H','3465']],
    bio: 'Shortstop y capitán histórico de los Yankees durante dos décadas, reconocido por liderazgo y trayectoria.',
    modelScale: 0.46,
    baseZ: 0.24,
    number: '2',
    role: 'SHORTSTOP',
    playerImage: 'assets/players/derek-jeter.png'
  },
  'ichiro-suzuki': {
    id: 'ichiro-suzuki',
    name: 'Ichiro Suzuki',
    team: 'Seattle Mariners',
    category: 'INTERNACIONAL',
    targetImage: 'assets/cards/ichiro-suzuki-front.png',
    mindFile: null,
    compileTarget: true,
    markerImage: 'assets/cards/ichiro-suzuki-front.png',
    model: 'assets/ar/models/pelota.glb',
    modelLabel: 'Pelota 3D · modelo provisional',
    features: { animations: true, info: true, narration: false, video: false, effects: true },
    qr: 'assets/qr/ichiro-suzuki-ar.png',
    stats: [['AVG','.311'],['HR','117'],['RBI','780'],['H','3089']],
    bio: 'Ícono japonés de Seattle, reconocido por contacto, velocidad y defensa.',
    modelScale: 0.46,
    baseZ: 0.24,
    number: '51',
    role: 'OUTFIELDER',
    playerImage: 'assets/players/ichiro-suzuki.png'
  }
};
